on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        required: false
        options:
          - TargetA
          - TargetB
          - TargetC

env:
  SAMPLE_VALUE: hello
  DEPLOY_DOMAIN: |
    ${{ fromJSON(
      format('{
        "TargetA": "{0}",
        "TargetB": "site-a.example.com"
      }', 'aaa'))[github.event.inputs.target] || 'fallback.example.com' }}\

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo -----
          echo XXX${{ env.DEPLOY_DOMAIN }}XXX
          echo -----
