on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        required: false
        options:
          - TargetA
          - TargetB
          - TargetC

env:
  SAMPLE_VALUE: ${{ secrets.SAMPLE_VALUE }}
  DEPLOY_DOMAIN: |
    ${{ fromJSON('{
      "TargetA": "$SAMPLE_VALUE",
      "TargetB": "site-a.example.com"
    }')[github.event.inputs.target] || 'fallback.example.com' }}\

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo -----
          echo XXX${{ env.DEPLOY_DOMAIN }}XXX
          echo -----
