on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        required: false
        options:
          - TargetA
          - TargetB
          - TargetC

env:
  DEPLOY_DOMAIN: hello

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo -----
          echo XXX${{ env.DEPLOY_DOMAIN }}XXX
          echo -----
